cache-key: &cache-key v1-dependencies-{{ checksum "pom.xml" }}

version: 2
jobs:
  build:
    docker:
    - image: maven:3-jdk-8-slim

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
    - checkout

    - restore_cache:
        keys:
        - *cache-key

    - run:
        name: Resolve depencies
        command: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: *cache-key

    - run:
        name: Test & Build
        command: mvn clean integration-test


